"""
Django settings for lucas project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-r%ucxzeyumw2)3+00s@b@jy&eqoat7v7ok%09jhdix*jvwxcgl"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'lungapp',
    'predictData',
    'studyData',
    'viewData',
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "lucas.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "lucas.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.sqlite3",
#         "NAME": BASE_DIR / "db.sqlite3",
#     }
# }

# MySQL 데이터베이스 설정
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": "lungcancer", # 사용자 요청 DB명
        "USER": "acorn",
        "PASSWORD": "acorn1234",
        "HOST": "34.61.113.204",
        "PORT": "3306",
        "OPTIONS": {
            "charset": "utf8mb4",
            "init_command": "SET sql_mode='STRICT_TRANS_TABLES'",
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "ko-KR"

TIME_ZONE = "Asia/Seoul"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static')
]

# media 폴더 목록에 생성해주기
MEDIA_URL = "media/"
MEDIA_ROOT = BASE_DIR / 'media'

# 데이터 경로
DATA_DIR = BASE_DIR / 'data'
LUNG_CANCER_CSV = DATA_DIR / 'lung_cancer_dataset.csv'

# 전역변수
LUNG_TARGET_NAME = 'LUNG_CANCER'   # 실제 타깃 컬럼명으로 교체
LUNG_EXCLUDE_FEATURES = ["patient_id", "lung_cancer"]
LUNG_CANCER_CSV = str(BASE_DIR / "data" / "lung_cancer_dataset.csv")


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# === Logging (Timeline & SQL) ===
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,

    "formatters": {
        "timeline": {
            "format": "[{asctime}] {levelname:<7} {name} :: {message}",
            "datefmt": "%Y-%m-%d %H:%M:%S",
            "style": "{",
        },
    },

    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "timeline",
        },
    },

    "loggers": {
        # 요청/오류 기본 로그 (원하면 유지)
        "django.request": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": True,
        },

        # 여러분 앱 흐름용 로거 (views.py에서 log = logging.getLogger("app.flow") 사용 가능)
        "app.flow": {
            "handlers": ["console"],
            "level": "DEBUG",
            "propagate": False,
        },

        # ORM SQL 로그 (많으면 INFO로 낮추거나 제거)
        "django.db.backends": {
            "handlers": ["console"],
            "level": "DEBUG",   # DEBUG: 전체 SQL, INFO: 더 적게
            "propagate": False,
        },
    },
}